spring:
  application:
    name: spring-cloud-consumer-ribbon

server:
  port: 8010

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/